import { createFileRoute } from "@tanstack/react-router";
import { BookMarked, Film, Lightbulb, Newspaper } from "lucide-react";
export const Route=createFileRoute("/implementation")({head:()=>({meta:[{title:"Implementation & Purpose | CES at SKH Lam Woo"},{name:"description",content:"How the CES curriculum connects knowledge, school values and real-world application."},{property:"og:title",content:"Implementation & Purpose | CES at SKH Lam Woo"},{property:"og:description",content:"Knowledge applied with truth, empathy, wisdom and responsibility."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:ImplementationPage});
const values=["Truth","Leadership","Passion","Humility","Wisdom","Optimism","Originality","Empathy","Responsibility"];
function ImplementationPage(){return <div className="page-space"><div className="site-container"><header className="page-intro"><p className="section-kicker">From knowing to doing · 知行合一</p><h1 className="page-title">Implementation</h1><p className="page-deck">We follow a philosophy that emphasises not only knowledge acquisition but also its meaningful application in real-world contexts.</p></header>
<section className="mt-16 grid gap-px bg-border border border-border md:grid-cols-3"><article className="practice-card"><Newspaper/><span>Student research</span><p>Contributing project work to the school’s scholarly magazines.</p></article><article className="practice-card"><Film/><span>Public knowledge</span><p>Creating and distributing informative videos on NGO platforms.</p></article><article className="practice-card"><BookMarked/><span>Recognised work</span><p>Earning external accolades through ability, initiative and dedication.</p></article></section>
<section className="editorial-section grid gap-12 md:grid-cols-[.7fr_1.3fr]"><div><p className="section-kicker">In practice</p><h2 className="section-title mt-5">Knowledge that travels.</h2></div><div className="prose-copy"><p>We actively promote and foster an environment in which students are not only imbibers of information but also its propagators. Our students have consistently contributed their research and project work to school’s scholarly magazines as evidence of this philosophy in action.</p><p>Furthermore, they have taken the initiative to create and distribute informative videos on various NGO platforms that reflect their acquired knowledge. This section details the external accolades and awards that our students have earned as a result of their abilities and dedication.</p></div></section>
</div><section className="bg-secondary"><div className="site-container py-20 md:py-28"><p className="section-kicker">Purposes · 課程宗旨</p><div className="mt-8 grid gap-12 md:grid-cols-[.8fr_1.2fr]"><h2 className="section-title">Echoing School’s Values and Ethos</h2><div className="prose-copy"><p>Our school values truth, leadership, passion, humility, wisdom, optimism, originality, empathy, and responsibility. This ethos is intricately woven into our curriculum. When all these elements are woven together in our curriculum, they effectively resonate with the values enshrined in our school’s motto.</p><blockquote>“The Truth Will Set You Free.”</blockquote></div></div><div className="mt-14 flex flex-wrap gap-2">{values.map(v=><span className="value-chip" key={v}>{v}</span>)}</div></div></section>
<section className="site-container py-20 md:py-28"><div className="grid gap-12 md:grid-cols-[.65fr_1.35fr]"><div><Lightbulb className="size-8 text-accent"/><p className="section-kicker mt-6">Curriculum Emphasis</p><h2 className="section-title mt-5">Values made visible.</h2></div><div className="prose-copy"><p>The emphasis on understanding different perspectives, backgrounds, and values reflects the search for truth and the belief that “The Truth Will Set You Free.” Leadership qualities include effective communication skills, a passion for public affairs, and the ability to make sound decisions.</p><p>The emphasis on personal reflection, self-awareness, and making responsible decisions demonstrates zeal and wisdom. Recognizing different groups and understanding different points of view demonstrate modesty and empathy.</p><p>Our curriculum’s components centered on making reasoned judgments, interpreting data, and comprehending economic and political systems demonstrate wisdom and originality. The push for positive interpersonal relationships and seeing how communities interconnect imply optimism.</p><p>Finally, encouraging open-mindedness, respect for all cultures, understanding and appreciation of the motherland, and safeguarding national security emphasizes empathy and responsibility.</p></div></div></section></div>}
